replace PdfMerger by PdfWriter
small fix to solve this issue:

```
pypdf.errors.DeprecationError: PdfMerger is deprecated and was removed in pypdf 5.0.0. Use PdfWriter instead.
```